'use client';
import { useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '../../context/AuthContext';

export default function QRScannerPage() {
  const { user, loading: authLoading } = useAuth();
  const router = useRouter();
  const html5QrRef = useRef(null);
  const [status, setStatus] = useState('idle'); // idle | starting | scanning | error | success
  const [errorMsg, setErrorMsg] = useState('');
  const [cameras, setCameras] = useState([]);
  const [selectedCamera, setSelectedCamera] = useState(null);
  const [scanned, setScanned] = useState(false);

  // Auth Protection
  useEffect(() => {
    if (!authLoading && !user) router.push('/login');
    if (!authLoading && user?.role !== 'student') router.push('/teacher/dashboard');
  }, [user, authLoading]);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (html5QrRef.current) {
        html5QrRef.current.stop().catch(() => {});
      }
    };
  }, []);

  const stopScanner = async () => {
    if (html5QrRef.current) {
      try {
        await html5QrRef.current.stop();
        html5QrRef.current = null;
      } catch (e) {
        console.error("Stop error", e);
      }
    }
  };

  const startScanner = async (cameraId) => {
    setStatus('starting');
    setErrorMsg('');

    // Small timeout to ensure the DOM element #qr-reader is rendered
    setTimeout(async () => {
      try {
        const { Html5Qrcode } = await import('html5-qrcode');

        if (html5QrRef.current) {
          await stopScanner();
        }

        const qrScanner = new Html5Qrcode('qr-reader');
        html5QrRef.current = qrScanner;

        const config = {
          fps: 10,
          qrbox: { width: 250, height: 250 },
          aspectRatio: 1.0,
        };

        // Use 'user' for PC/Laptops if 'environment' fails
        const cameraConfig = cameraId ? cameraId : { facingMode: 'environment' };

        await qrScanner.start(
          cameraConfig,
          config,
          (decodedText) => {
            if (scanned) return;
            handleScanSuccess(decodedText, qrScanner);
          },
          () => {} // silent frame errors
        );

        setStatus('scanning');
      } catch (err) {
        console.error('Scanner error:', err);
        setStatus('error');
        if (err.message?.includes('permission') || err.name === 'NotAllowedError') {
          setErrorMsg('Camera access denied. Please allow camera permission in browser settings.');
        } else {
          setErrorMsg('Could not start camera. Please ensure no other app is using it.');
        }
      }
    }, 300);
  };

  const handleScanSuccess = async (decodedText, scanner) => {
    setScanned(true);
    try { await scanner.stop(); } catch {}
    html5QrRef.current = null;
    setStatus('success');

    let sessionId = null;
    try {
      const url = new URL(decodedText);
      sessionId = url.searchParams.get('session');
    } catch {
      if (decodedText.length > 10) sessionId = decodedText.trim();
    }

    if (!sessionId) {
      setStatus('error');
      setErrorMsg('Invalid QR code. This QR was not generated by AttendX.');
      setScanned(false);
      return;
    }

    if (navigator.vibrate) navigator.vibrate(100);

    setTimeout(() => {
      router.push(`/scan?session=${encodeURIComponent(sessionId)}`);
    }, 800);
  };

  const handleStartClick = async () => {
    try {
      const { Html5Qrcode } = await import('html5-qrcode');
      const devices = await Html5Qrcode.getCameras();
      setCameras(devices);
      
      if (devices.length > 0) {
        const backCam = devices.find(d => /back|rear|environment/i.test(d.label));
        const camId = backCam?.id || devices[0]?.id;
        setSelectedCamera(camId);
        startScanner(camId);
      } else {
        startScanner(null);
      }
    } catch (e) {
      startScanner(null);
    }
  };

  const handleRetry = () => {
    setScanned(false);
    setStatus('idle');
    setErrorMsg('');
  };

  if (authLoading) return <FullPageLoader />;

  return (
    <div style={{ minHeight: '100vh', background: '#0f172a', color: 'white', display: 'flex', flexDirection: 'column', alignItems: 'center', padding: '24px 16px' }}>
      
      {/* Header */}
      <div style={{ width: '100%', maxWidth: 440, marginBottom: 28, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
         <button onClick={() => { stopScanner(); router.push('/student/dashboard'); }} style={{ background: 'none', border: 'none', color: '#94a3b8', cursor: 'pointer' }}>
           ← Dashboard
         </button>
         <div style={{ fontWeight: 800, fontSize: 18, color: '#7c3aed' }}>AttendX</div>
         <div style={{ width: 40 }} /> 
      </div>

      <div style={{ textAlign: 'center', marginBottom: 30 }}>
        <h1 style={{ fontSize: 24, fontWeight: 800, marginBottom: 8 }}>Scan QR Code</h1>
        <p style={{ color: '#94a3b8', fontSize: 14 }}>Point camera at the teacher's screen</p>
      </div>

      {/* Main Container */}
      <div style={{ width: '100%', maxWidth: 440, position: 'relative' }}>
        
        {/* THE FIX: DIV is always present but hidden/shown based on state */}
        <div 
          id="qr-reader" 
          style={{ 
            display: status === 'scanning' ? 'block' : 'none',
            width: '100%',
            borderRadius: '20px',
            overflow: 'hidden',
            border: '2px solid #7c3aed',
            boxShadow: '0 0 20px rgba(124, 58, 237, 0.3)'
          }} 
        />

        {status === 'idle' && (
          <div style={{ padding: 40, background: '#1e293b', borderRadius: 20, textAlign: 'center' }}>
            <div style={{ fontSize: 50, marginBottom: 20 }}>📸</div>
            <button className="btn-primary" onClick={handleStartClick} style={{ width: '100%', background: '#7c3aed', color: 'white', padding: '14px', borderRadius: '12px', border: 'none', fontWeight: 700, cursor: 'pointer' }}>
              Open Camera
            </button>
          </div>
        )}

        {status === 'starting' && (
          <div style={{ textAlign: 'center', padding: 40 }}>
            <div className="spinner" />
            <p>Initializing camera...</p>
          </div>
        )}

        {status === 'error' && (
          <div style={{ padding: 30, background: '#451a1a', borderRadius: 20, textAlign: 'center', border: '1px solid #f43f5e' }}>
            <p style={{ color: '#f43f5e', marginBottom: 20 }}>{errorMsg}</p>
            <button onClick={handleRetry} style={{ background: '#f43f5e', color: 'white', padding: '10px 20px', borderRadius: '8px', border: 'none' }}>Try Again</button>
          </div>
        )}

        {status === 'success' && (
          <div style={{ textAlign: 'center', padding: 40 }}>
            <div style={{ fontSize: 50 }}>✅</div>
            <p style={{ color: '#10b981', fontWeight: 700 }}>Attendance Marked!</p>
          </div>
        )}
      </div>

      <style jsx>{`
        .spinner {
          width: 40px; height: 40px;
          border: 4px solid rgba(124, 58, 237, 0.2);
          border-top: 4px solid #7c3aed;
          border-radius: 50%;
          animation: spin 1s linear infinite;
          margin: 0 auto 20px;
        }
        @keyframes spin { to { transform: rotate(360deg); } }
        #qr-reader video { object-fit: cover !important; }
      `}</style>
    </div>
  );
}

function FullPageLoader() {
  return <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: '#0f172a', color: 'white' }}>Loading...</div>;
}
